### ISSUE TITLE
Admin Guide Add-on: Project Limits and Quotas

### ISSUE THREAD

**Issue by buuhsmead** [redhat-cop/openshift-playbooks#257]
Would be nice if there is a section for cluster admins to set company policies on project limits and resource quotas. (an item always encountered during engagements).
For instance the following default project-request template has taken (to much) effort to get to a working format:

```
apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: project-request
objects:
- apiVersion: project.openshift.io/v1
  kind: Project
  metadata:
    annotations:
      openshift.io/description: ${PROJECT_DESCRIPTION}
      openshift.io/display-name: ${PROJECT_DISPLAYNAME}
      openshift.io/requester: ${PROJECT_REQUESTING_USER}
    creationTimestamp: null
    name: ${PROJECT_NAME}
  spec: {}
  status: {}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-pullers
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-puller
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: system:serviceaccounts:${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:image-builders
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:image-builder
  subjects:
  - kind: ServiceAccount
    name: builder
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: system:deployers
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: system:deployer
  subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: ${PROJECT_NAME}
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: admin
    namespace: ${PROJECT_NAME}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: admin
  subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: ${PROJECT_ADMIN_USER}
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: compute-resources
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      cpu: "1"
      memory: 2Gi
- apiVersion: v1
  kind: ResourceQuota
  metadata:
    name: storage-resources
    namespace: ${PROJECT_NAME}
  spec:
    hard:
      persistentvolumeclaims: "10"
      requests.storage: 10Gi
- apiVersion: v1
  kind: LimitRange
  metadata:
    name: compute-limits
    namespace: ${PROJECT_NAME}
  spec:
    limits:
      - type: "Pod"
        max:
          cpu: 1000m
          memory: 2Gi
        min:
          cpu: 100m
          memory: 128Mi
      - type: "Container"
        max:
          cpu: 900m
          memory: 1900Mi
        min:
          cpu: 100m
          memory: 128Mi
        defaultRequest:
          cpu: 200m
          memory: 512Mi
parameters:
- name: PROJECT_NAME
- name: PROJECT_DISPLAYNAME
- name: PROJECT_DESCRIPTION
- name: PROJECT_ADMIN_USER
- name: PROJECT_REQUESTING_USER
```
